### ISSUE TITLE
Adopt the new iTwins API

### ISSUE THREAD

**Issue by calebmshafer** [iTwin/viewer#215] opened 2022-09-01 15:39 UTC
Update the Viewer to use the new [iTwins API](https://developer.bentley.com/apis/itwins/) instead of the [Projects API](https://developer.bentley.com/apis/projects/).

- [x]  Wait for the iTwin client library
- [x] Wait for and update to the iModels clients library

**Comment by aruniverse** [comment] 2023-08-23 21:44
partial duplicate of https://github.com/iTwin/viewer/issues/284
the viewer pkgs itself never relied on the projects-api; the desktop app & template did, and those were updated in above pr

**Closed by aruniverse** 2023-08-23 21:44 UTC
Labels: enhancement
