### ISSUE TITLE
Conditional rendering of viewer not working

### ISSUE THREAD

**Issue by monikaw-20** [iTwin/viewer#340] opened 2024-12-06 14:34 UTC
We want to use Blank viewer and normal viewer conditionally. initially blank viewer is loaded then if itwinId and iModelId exists we pass those as new props and try to load the normal viewer. Same access token is used it is working for first blank viewer but not working again when I try to load it with itwinId and iModel as a normal viewer:
 
We are using BrowserAuthClient. Earlier we were only using normal viewer and it was working
 
<Viewer {...viewerProps} />

![Image](https://github.com/user-attachments/assets/3a722296-d134-47a5-9cd5-15088f98bdc9)

Getting an error -

![Image](https://github.com/user-attachments/assets/fb4059aa-95e0-4e7b-ac0a-09935d974237)

**Comment by williamzqr** [comment] 2024-12-06 19:21
Can we get a minimal reproduction? That would be really helpful, thank you!!

**Comment by monikaw-20** [comment] 2024-12-09 06:28
@williamzqr You can reproduce it here - https://www.itwinjs.org/sandboxes/MonikaWalunjkar/mw_test_viewer

**Comment by anmolshres98** [comment] 2024-12-09 23:28
Hi @monikaw-20 , is there a reason you are attempting to render a blank viewer instead of a loading screen of some sort?

**Comment by monikaw-20** [comment] 2024-12-10 04:52
@anmolshres98 @williamzqr We want to display default view at least the background Map until user has selected iTwin/iModel, so we thought of displaying a blank viewer

**Comment by anmolshres98** [comment] 2024-12-10 19:36
@monikaw-20 

@williamzqr and I looked deeper into your code and based on the use-case you have mentioned, the following code should be able to cover it (we are using the same values you want to but just passing them in differently than you have it). 

Sandbox:
https://www.itwinjs.org/sandboxes/AnmolShrestha/coleen-the-amethyst-herring-390

If for some reason you cannot access the sandbox, here is the full src code:
```tsx
import React, { useEffect } from "react";
import { Viewer } from "@itwin/web-viewer-react";
import { authClient } from "./common/AuthorizationClient";
import { mapLayerOptions } from "./common/MapLayerOptions";
import { Cartographic } from "@itwin/core-common";
import { Range3d } from "@itwin/core-geometry";

const ViewportFrontstageApp = () => {
const [iTwinId, setITwinId] = React.useState<string|null>(null);
const [iModelId, setIModelId] = React.useState<string|null>(null);
  /** Sign-in */
  useEffect(() => {
    void authClient.signIn();
  }, []);

  const onButtonClick = () => {
    setITwinId(process.env.IMJS_ITWIN_ID)
    setIModelId(process.env.IMJS_IMODEL_ID)
  };

  /** The sample's render method */
  return(<>
  <button onClick={onButtonClick}>Click this to switch Viewer</button>
  <Viewer
        iTwinId={iTwinId ?? ""}
        iModelId={iModelId ?? ""}
        authClient={authClient}
        blankConnectionViewState={{ viewFlags: { backgroundMap: true } }}
        location={Cartographic.fromDegrees({
          longitude: -83.686694,
          latitude: 37.065757,
          height: 0,
        })}
        extents={new Range3d(-40000, -40000, -100, 40000, 40000, 100)}
        mapLayerOptions={mapLayerOptions}
        enablePerformanceMonitors= {false}
        defaultUiConfig= {{
          hideStatusBar: true,
          hideToolSettings: true,
        }}
        theme={process.env.THEME ?? "dark"}
  /></>) ;
};

export default ViewportFrontstageApp;

```

In terms of what was going and why you were seeing the error you were seeing. We are not fully sure but it seems to me that your Viewer setup should have thrown a missingConnectionProps error, which for some reason it wasn't.

If this works for you, feel free to close this issue out.

**Comment by anmolshres98** [comment] 2024-12-10 19:37
Additionally, feel free to check out the test viewers here: https://github.com/iTwin/viewer/tree/master/packages/apps/web-viewer-test/src/components/home as reference/examples

**Comment by monikaw-20** [comment] 2024-12-11 05:18
@anmolshres98 @williamzqr There are issues in the code you shared. You can see the error message here:

![Image](https://github.com/user-attachments/assets/2afc66e6-4c9c-4e0c-8274-bbedfdfe92cb)

**Comment by anmolshres98** [comment] 2024-12-11 06:08
It seems that blank viewer props() and connection viewer props are not allowed to overlap, that is why ts is complaining. From the type definition for the props: 
```ts
type WebViewerProps = XOR<ConnectedViewerWebProps, BlankViewerWebProps> & WebInitializerParams;
```
I am not sure why this is either. For now, since the functionality of the viewer is working as intended for your usecase, I would suggest turning off ts error for that line by doing so:
```tsx
/** The sample's render method */
  return(<>
  <button onClick={onButtonClick}>Click this to switch Viewer</button>
  {/* @ts-ignore */}
  <Viewer
        iTwinId={iTwinId ?? ""}
        iModelId={iModelId ?? ""}
        authClient={authClient}
        blankConnectionViewState={{ viewFlags: { backgroundMap: true } }}
        location={Cartographic.fromDegrees({
          longitude: -83.686694,
          latitude: 37.065757,
          height: 0,
        })}
        extents={new Range3d(-40000, -40000, -100, 40000, 40000, 100)}
        mapLayerOptions={mapLayerOptions}
        enablePerformanceMonitors= {false}
        defaultUiConfig= {{
          hideStatusBar: true,
          hideToolSettings: true,
        }}
        theme={process.env.THEME ?? "dark"}
  /></>) ;
```

@aruniverse @ben-polinsky Do you know why the props aren't allowed to overlap and what would be the suggestion for @monikaw-20 's usecase here? Thanks.

**Comment by ben-polinsky** [comment] 2024-12-11 14:38
Hi. The Viewer as-is hasn't been designed to switch seamlessly from a "BlankConnection" without an iModelId to one with an iModelId. This is the reason the props are mutually exclusive.

**Comment by anmolshres98** [comment] 2024-12-11 17:57
Hi @monikaw-20 , based on Ben's response since the Viewer component as-is isn't currently designed to handle overlapping of connectionProps and blankStateProps. Overlapping those props when not recommended could lead to undefined behavior.  I would suggest having a wrapper component to handle the conditional logic and the wrapper calls the Viewer while passing props conditionally to it. This way you can achieve having conditional rendering of your viewer and in your wrapper component you can have memoization and other functionalities to avoid unnecessary re-renders.

Check my code here consistent with your end goals: 
https://www.itwinjs.org/sandboxes/AnmolShrestha/lorne-the-olive-slug-763

**Comment by monikaw-20** [comment] 2024-12-12 10:33
@anmolshres98  Thanks for the code but it is not behaving as expected in actaul Application. Anyway we could use the default iTwinId and iModelId settings for now instead of using the blank viewer

**Comment by anmolshres98** [comment] 2024-12-12 16:04
Sorry to heart tat @monikaw-20 . The code is working in the sandbox but not in your actual application? We would love to help you so if possible could you give me src code to your application so that I could better help you?

**Comment by anmolshres98** [comment] 2024-12-12 21:45
Thanks for sharing @monikaw-20 , I cloned your repo and tried running your app locally but I ran into issues with it. (Perhaps because I am using MacOS 🤔).

Either way, I looked at your code and so far it doesn't seem to be structured in the same manner as the one I linked in [my sandbox](https://www.itwinjs.org/sandbox/AnmolShrestha/lorne-the-olive-slug-763). 

I have created a repo off of the base viewer template and tried to have my viewer code match closer to what you have on your repo: https://github.com/anmolshres98/mw-test-viewer/blob/main/src/NetworkViewer.tsx

Please take a look at the new repo I created and try and get your application code closer to what I have and check to see if that works. You can also clone the repo, create a new branch, edit the code so that it better resembles your app code and try and push that so that I can debug and help you faster on my end.

**Comment by monikaw-20** [comment] 2024-12-13 05:31
@anmolshres98 Code was on my local branch. It is pushed here - https://dev.azure.com/bentleycs/AWLAM/_git/AWLAM-WorkZone-Management-UI?version=GBMonika/Task_1572259

It is similar to what you have sent still not working:

![Image](https://github.com/user-attachments/assets/f5b035d4-2c08-4c3a-a9e6-0afa54371976)

**Comment by anmolshres98** [comment] 2024-12-13 06:39
@monikaw-20 this looks like auth error and not the app setup itself erroring necessarily.
Here are some suggestions to better isolate and debug:
- check the network request and response, you can use your local debugger or check network tab in browser
- Make sure the issuer url matches the env for api env; if request being made to qa- then issuer should be qa-ims and so on
- Make sure scopes are correct
- Make sure the itwin/imodel exist in the same env has above -- qa itwin if qa access token and so on

This should greatly help you isolate the issue and also allow us to better help you since if the issue is with access token and auth, we don't have the same config as you do so it would be harder for us to help.

**Comment by monikaw-20** [comment] 2024-12-13 07:22
@anmolshres98 I have emailed you the details of the request

**Comment by anmolshres98** [comment] 2024-12-16 16:16
@monikaw-20 Bringing this conversation back to this thread so that others who are facing similar issue can benefit from looking at this thread 😄 .

This response is based on this email message to me: 
![Image](https://github.com/user-attachments/assets/25d8edc6-91f7-4246-9c77-dad613239f28)


I checked the seq log for that request you sent me and it seems that there is a mismatch between token issuer and the issuer the api expects your token to be. Namely, since the api is `api.bentley.com`, the issuer is expected to be `ims.bentley.com`. However, for the above request the token you are passing in was issued by `qa-ims.bentley.com`. If your want to send requests to the qa api, you want to send requests to `qa-api.bentley.com` using a token issued by `qa-ims.bentley.com` and vice-versa for `api.bentley.com`. The mismatch between them will throw a `401` response from the api. You should also make sure that the iModel exists in the appropriate environment. You can check the [log here](https://seq.bentley.com/#/events?filter=ActivityId%3D%2268b5abaa-b304-473d-a600-0b2c70869c01%22&from=2024-12-16T05:00:00.000Z&to=2024-12-16T06:00:00.000Z).

![Image](https://github.com/user-attachments/assets/387c4c15-fca1-4ee6-badd-fd5c1f8c87d4)

This is not a error on the `Viewer` component per se, however your might be missing passing `qa-` for `environment` or `prefix` params in some of your client api calls. Please check those calls and make sure the token, api, and iModel/iTwin are all in the same environment.

I advise using [tools to decode](https://stackoverflow.com/questions/38552003/how-to-decode-jwt-token-in-javascript-without-using-a-library) the token you are passing in. There are online webpages that do this for you but usage of those are discouraged due to security concerns. Additionally, I suggest using the api webpage directly to make requests before using the app to make the requests too if you encounter errors: https://developer.bentley.com/apis/imodels-v2/operations/get-imodel-changesets/. Both these strategies should help you isolate the issue to one area or the other so that you can debug and fix things faster.

Once you have figured out the code issue try the Viewer again and let us know if you are still seeing issues.

**Comment by anmolshres98** [comment] 2024-12-17 16:10
The additional issue @monikaw-20 had was related to internal implementation details specific to Bentley. I was able to help her privately and resolve her remaining issues.

My responses above address the question initially asked in this issue and relevant to this public repo. Hence, going to close this  out.

**Closed by anmolshres98** 2024-12-17 16:10 UTC
